name: pest

on:
  push:

jobs:
  pest:
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.0]
        laravel: [^9.0, ^8.0]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: ^8.0
            dependency-version: prefer-lowest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, mbstring, zip, pcntl, intl
          coverage: xdebug
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      - run: vendor/bin/pest --coverage --coverage-html=.coverage
      - uses: actions/upload-artifact@v2
        with:
          name: "Coverage: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}"
          path: ./.coverage
  infection:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.0
          extensions: dom, curl, mbstring, zip, pcntl, intl
          coverage: xdebug
      - run: composer install --no-interaction --no-scripts
      - run: vendor/bin/infection -j2 --logger-github
