name: pest

on:
  push:

jobs:
  pest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.0
          extensions: dom, curl, mbstring, zip, pcntl, intl
          coverage: xdebug
      - run: composer install --no-interaction --no-scripts
      - run: vendor/bin/pest --coverage --coverage-html=.coverage
      - uses: actions/upload-artifact@v2
        with:
          name: Coverage
          path: ./.coverage
  infection:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.0
          extensions: dom, curl, mbstring, zip, pcntl, intl
          coverage: xdebug
      - run: composer install --no-interaction --no-scripts
      - run: git fetch --depth=1 origin $GITHUB_BASE_REF
      - run: vendor/bin/infection --test-framework=pest -j2 --git-diff-filter=A --git-diff-base=origin/$GITHUB_BASE_REF --logger-github --ignore-msi-with-no-mutations --only-covered
